# -*- coding: utf-8 -*-
"""BenjaminDillon-AymanSharieff-COIL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15w-HJUPiMESoted5yn4F9Ahv4JfY5PL0
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from ipywidgets import interact, IntSlider

import warnings
warnings.filterwarnings("ignore")

# Dataset real (StudentsPerformance)
kaggle_url = "https://raw.githubusercontent.com/BenjaminDillon2003/early-academic-risk-prediction/e4b3182e231541a767f7af61080c28fb50ac75bf/synthetic_dataset.csv"
kaggle_data = pd.read_csv(kaggle_url)

# Dataset sintético
synthetic_url = "https://raw.githubusercontent.com/BenjaminDillon2003/early-academic-risk-prediction/e4b3182e231541a767f7af61080c28fb50ac75bf/synthetic_dataset.csv"
synthetic = pd.read_csv(synthetic_url)

kaggle_data.head(), synthetic.head()

synthetic = synthetic.rename(columns={
    "math score": "math_score",
    "reading score": "reading_score",
    "writing score": "writing_score",
    "test preparation course": "test_prep"
})

synthetic.columns

synthetic["avg_score"] = (
    synthetic["math_score"] +
    synthetic["reading_score"] +
    synthetic["writing_score"]
) / 3

def assign_risk(row):
    risk = 0

    # Academic risk
    if row['avg_score'] < 60:
        risk += 2
    elif row['avg_score'] < 75:
        risk += 1

    # Lunch socioeconomic proxy
    if row["lunch"] == "free/reduced":
        risk += 1

    # Test prep helps reduce risk
    if row["test_prep"] == "completed":
        risk -= 1

    if risk >= 2:
        return "High"
    elif risk == 1:
        return "Medium"
    else:
        return "Low"

synthetic["risk_level"] = synthetic.apply(assign_risk, axis=1)

X = synthetic[["math_score","reading_score","writing_score"]]
y = synthetic["risk_level"].map({"Low":0, "Medium":1, "High":2})

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

model = LogisticRegression(max_iter=2000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, cmap="Blues",
            xticklabels=["Low","Medium","High"],
            yticklabels=["Low","Medium","High"])
plt.title("Confusion Matrix")
plt.show()

def predict_risk(math_score, reading_score, writing_score):

    X_new = pd.DataFrame([{
        "math_score": math_score,
        "reading_score": reading_score,
        "writing_score": writing_score
    }])

    pred = model.predict(X_new)[0]

    if pred == 0:
        print("Low Risk")
    elif pred == 1:
        print("Medium Risk")
    else:
        print("High Risk")

interact(
    predict_risk,
    math_score=IntSlider(min=0,max=100,value=70),
    reading_score=IntSlider(min=0,max=100,value=70),
    writing_score=IntSlider(min=0,max=100,value=70)
)